name: spigot-example
version: 1.0-SNAPSHOT
main: com.example.spigot.App
api-version: '1.20'
description: My very first test with spigot

commands:
  set-pvp:
    description: Modifies global pvp behavior
    usage: /set-pvp [true|false]
    aliases:
      - pvp
      - togglepvp
      - setpvp
  
  heal:
    description: Heals player of all its health
    usage: /heal [player]
